### ISSUE TITLE
Is there any plan to add tabs?

### ISSUE THREAD

**Issue by xiaojiangding** [qiuyaofan/iShow#5]
Is there any plan to add tabs?

**Comment by qiuyaofan** [comment]
what tabs?

**Comment by qiuyaofan** [comment]
what tabs? @xiaojiangding

**Comment by yudan215** [comment]
请问前端生成JSON以后,后端如何生成对应的HTML`是否有DEMO

**Comment by qiuyaofan** [comment]
你看ishow-mobile文件夹的就是，通过json配置去渲染出手机端页面 @yudan215

**Comment by yudan215** [comment]
谢谢回复，看到了，但是还是有些不明白，能否给个联系方式方便请教

**Comment by qiuyaofan** [comment]
邮箱 ：625111246@qq.com @yudan215
