### ISSUE TITLE
整套UI做的不错，但貌似还缺很多功能

### ISSUE THREAD

**Issue by rendq** [qiuyaofan/iShow#7]
1. 预览功能（用模拟器预览）
2. 动画预览，
3. 图集（swiper控件）
4. 表单信息数据后台

**Comment by qiuyaofan** [comment]
动画预览在动画编辑有，只是循环次数的没显示，我看易企秀也一样。
手机端的没深入，主要是编辑器而已，第四不在前端范围内没做。
手机端可以自己扩展的 完全分离的

**Comment by qiuyaofan** [comment]
不过有时间确实可以继续加上手机端的，之前重心都在编辑器 @rendq
