### ISSUE TITLE
大佬，能写一下设计思路么

### ISSUE THREAD

**Issue by Mr-xue** [qiuyaofan/iShow#8]
整体功能的规划，及设计思路，关于数据结构的设计思路。
我最近也想自己写一套练练手，但是感觉有时候感觉思路上有断层

**Comment by qiuyaofan** [comment]
基本思路就是通过控制json去控制页面的属性样式，所有页面是一个json数组，一个页面是一个json,页面内元素也是一个json，里面包括很多属性（我首页有列出来），你想加什么去什么都很方便。
自己定好想要的功能点，就可以去设计了，实践出真知，你动手写一写就知道了
