### ISSUE TITLE
运行报错 前端

### ISSUE THREAD

**Issue by 910758447** [qiuyaofan/iShow#9]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! juicy@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the juicy@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by qiuyaofan** [comment]
是不是 juicy@1.0.0没装成功
cnpm install  juicy试试 或者重新安装

**Comment by 910758447** [comment]
哦，谢谢
